namespace Lopes.Anuncio.Domain.Enums
{
    public enum Portal
    {
        Zap = 68,

        //TODO: corresponder numero do enum com o id do veículo na tabela dbcrm.dbo.tb_veic_veiculo
        AgenteProduto = 1,
        ProdutoWeb = 3,
        Criteo = 4,
        Generico = 5,
        TiqueProdutos = 6,
        GazetaDoPovo = 7,
        Creci = 8,
        I123 = 9,
        Trovit = 10,
        Struq = 11,
        ProdutoAVenda = 12,
        LinkLar = 13,
        Olx = 14,
        PenseProdutos = 15,
        Vericia = 16,
        VivaReal = 17,
        Nuroa = 18,
        Moving = 19,
        Tatri = 20,
        MercadoLivre = 21,
        Ducati = 22,
        Lancamentos = 23,
        ThaLancamentos = 24,
        SociasLancamento = 25,
        Mitula = 26,
        LinksAtendimento = 27,
        SiteMap = 28,
        Mapa = 29,
        DadosPorPlanilha = 30,
        RedeGazeta = 31,
        ChaveFacil = 32,
        SiteMapSearchAddress = 33,
        SiteMapMaphAddress = 34,
        AverageRanking = 35,
        Wprodutos = 36,
        Properaty = 37,
        DadosProprietario = 38,
        LuxuryEstate = 39,
        ZLProduto = 40,
        PadraoLopesJson = 41,
        Plugprodutos = 42,
        ZNProduto = 43,
        Epungo = 44,
        GestaoReal = 45,
        PortalPratico = 46,
        DPAGoogle = 47,
        LugarCerto = 48,
        ZOProduto = 49,
        ABCProduto = 50,
        IMudou = 51,
        Facebook = 52,
        ShopBack = 53,
        RTBHouse = 54,
        Igglu = 55,
        Chiligum = 56,
        Klikey = 57,
        CasaMineira = 58,
        DFProdutos = 59,
        ChavesNaMao = 60,
        SiteMapIndex = 61,
        CliqueiMudei = 62,
        Companhia = 63,
        Casafy = 64,
        OlhoMagico = 65,
        ZapWay = 934
    }
}
