namespace Lopes.SC.ExportacaoAnuncio.Domain.Enums
{
    /// <summary>
    /// Veículo de mídia (tabela DBCRM.dbo.tb_veic_veiculo)
    /// </summary>
    public enum Portal
    {
        AgenteImovel = 623,
        Zap = 68,
        CasaMineira = 729,
        I123 = 622,


        //TODO: mudar números para bater com id da tabela
        ImovelWeb = 3,
        Criteo = 4,
        Generico = 5,
        TiqueImoveis = 6,
        GazetaDoPovo = 7,
        Creci = 8,
        Trovit = 10,
        Struq = 11,
        ImovelAVenda = 12,
        LinkLar = 13,
        Olx = 14,
        PenseImoveis = 15,
        Vericia = 16,
        VivaReal = 17,
        Nuroa = 18,
        Moving = 19,
        Tatri = 20,
        MercadoLivre = 21,
        Ducati = 22,
        Lancamentos = 23,
        ThaLancamentos = 24,
        SociasLancamento = 25,
        Mitula = 26,
        LinksAtendimento = 27,
        SiteMap = 28,
        Mapa = 29,
        DadosPorPlanilha = 30,
        RedeGazeta = 31,
        ChaveFacil = 32,
        SiteMapSearchAddress = 33,
        SiteMapMaphAddress = 34,
        AverageRanking = 35,
        Wimoveis = 36,
        Properaty = 37,
        DadosProprietario = 38,
        LuxuryEstate = 39,
        ZLImovel = 40,
        PadraoLopesJson = 41,
        Plugimoveis = 42,
        ZNImovel = 43,
        Epungo = 44,
        GestaoReal = 45,
        PortalPratico = 46,
        DPAGoogle = 47,
        LugarCerto = 48,
        ZOImovel = 49,
        ABCImovel = 50,
        IMudou = 51,
        Facebook = 52,
        ShopBack = 53,
        RTBHouse = 54,
        Igglu = 55,
        Chiligum = 56,
        Klikey = 57,
        DFImoveis = 59,
        ChavesNaMao = 60,
        SiteMapIndex = 61,
        CliqueiMudei = 62,
        Companhia = 63,
        Casafy = 64,
        OlhoMagico = 65,
        ZapWay = 934
    }

    public enum Veiculo
    {
        EmailMarketing = 28,
        Domingo = 76,
        DomingoNovoFormato = 76,
        DomingoComFoto = 76,
        Quinta = 76,
        QuintaNovoFormato = 76,
        Terça = 76,
        DiárioDoNordeste = 661,
        OPovo = 662,
        ComFoto = 700,
        Mosquito = 700,
        RevistaRede = 675,
        Zap = 68,
        Moving = 636,
        Imóvelàvenda = 648,
        ImóvelWeb = 38,
        VivaReal = 64,
        MercadoLivre = 42,
        CRECI = 701,
        P123i = 622,
        TiqueImóveis = 619,
        Tatri = 702,
        Trovit = 658,
        Mitula = 650,
        SiteEmpresa = 703,
        AgenteImóvel = 623,
        LuxuryEstate = 706,
        ZLImóveis = 631,
        ABCImóveis = 633,
        Properati = 699,
        PlugImóveis = 704,
        ZNImóveis = 637,
        Epungo = 714,
        OLX = 653,
        GestãoReal = 716,
        ZOImóveis = 629,
        ImóvelPrático = 720,
        WImóveis = 616,
        DFAqui = 721,
        LugarCerto = 40,
        iMudou = 723,
        Igglu = 724,
        CasaMineira = 729,
        Klikey = 730,
        DFImóveis = 763,
        ChavesnaMão = 765,
        CliqueiMudei = 766,
        ChaveFácil = 801,
        Campainha = 802,
        Casafy = 830,
        OlhoMágico = 901,
        ZAPWay = 947,
    }
}